package zcylas.totality.client.vfx.explosion;

import com.mojang.blaze3d.PrimitiveTopology;
import com.mojang.blaze3d.buffers.GpuBuffer;
import com.mojang.blaze3d.buffers.GpuBufferSlice;
import com.mojang.blaze3d.pipeline.BlendFunction;
import com.mojang.blaze3d.pipeline.ColorTargetState;
import com.mojang.blaze3d.pipeline.DepthStencilState;
import com.mojang.blaze3d.pipeline.RenderPipeline;
import com.mojang.blaze3d.platform.CompareOp;
import com.mojang.blaze3d.systems.RenderPass;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.systems.TimerQuery;
import com.mojang.blaze3d.textures.FilterMode;
import com.mojang.blaze3d.vertex.BufferBuilder;
import com.mojang.blaze3d.vertex.ByteBufferBuilder;
import com.mojang.blaze3d.vertex.DefaultVertexFormat;
import com.mojang.blaze3d.vertex.MeshData;
import com.mojang.blaze3d.vertex.VertexFormat;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.fabric.api.client.rendering.v1.level.LevelRenderEvents;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.BindGroupLayouts;
import net.minecraft.client.renderer.MappableRingBuffer;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.state.level.CameraRenderState;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.HitResult;
import net.minecraft.world.phys.Vec3;
import net.minecraft.world.phys.shapes.CollisionContext;
import org.jetbrains.annotations.Nullable;
import org.joml.Matrix4f;
import org.joml.Vector3f;
import org.lwjgl.system.MemoryUtil;
import zcylas.totality.Totality;
import zcylas.totality.api.core.util.VerificationReporter;
import zcylas.totality.client.vfx.explosion.FireExplosion.Element;
import zcylas.totality.client.vfx.explosion.FireExplosion.Kind;
import zcylas.totality.client.vfx.explosion.dev.FireballV2Dev;
import zcylas.totality.client.vfx.glow.EmissiveBuffer;
import zcylas.totality.client.vfx.glow.EmissiveGlow;
import zcylas.totality.client.vfx.glow.EmissiveSource;

import java.util.ArrayList;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalDouble;

/**
 * Draws every live {@link FireExplosion} (VFX Experiment 3, Fireball V2 phase B2): all fire elements of all explosions
 * are evaluated, sorted back to front and drawn in <b>one</b> draw call with {@code core/vfx_fire}, premultiplied-alpha
 * blending, reversed-Z depth test ({@code GREATER_THAN_OR_EQUAL}) and no depth writes, at
 * {@code BEFORE_TRANSLUCENT_TERRAIN} (the Heat Vision V2 pattern). Elements fade out close to the camera so an
 * explosion around the camera tints the view instead of filling it.
 *
 * <p>The ignition core and the hottest elements also contribute an emissive part to the Totality Emissive Rendering
 * Layer (B4): smaller than the fire they come from, so the bloom haloes the white-hot centre and gold heart without
 * washing out the orange body, red edges and soot. Each explosion reports a demand of at most 1 (its brightest moment)
 * to the layer's {@code fireball} budget group, so many overlapping explosions are scaled down together. Bloom is
 * screen-space glow, not world lighting: no block is lit by this.
 */
public final class FireExplosionRenderer {

    private static final RenderPipeline PIPELINE = RenderPipelines.register(RenderPipeline.builder(RenderPipelines.GLOBALS_SNIPPET)
            .withLocation(Identifier.fromNamespaceAndPath(Totality.MOD_ID, "pipeline/vfx_fire"))
            .withBindGroupLayout(BindGroupLayouts.MATRICES_PROJECTION)
            .withBindGroupLayout(BindGroupLayouts.SAMPLER0)
            .withVertexShader(Identifier.fromNamespaceAndPath(Totality.MOD_ID, "core/vfx_fire"))
            .withFragmentShader(Identifier.fromNamespaceAndPath(Totality.MOD_ID, "core/vfx_fire"))
            .withColorTargetState(new ColorTargetState(BlendFunction.TRANSLUCENT_PREMULTIPLIED_ALPHA))
            .withVertexBinding(0, DefaultVertexFormat.POSITION_TEX_COLOR)
            .withPrimitiveTopology(PrimitiveTopology.QUADS)
            .withDepthStencilState(new DepthStencilState(CompareOp.GREATER_THAN_OR_EQUAL, false))
            .withCull(false)
            .build());

    /**
     * The fire's turbulence, precomputed (B5): three independent tileable fbm fields that the shader samples instead of
     * evaluating value-noise octaves per pixel (generated by Context/Tools/vfx-fireball-v2/make_fire_noise.py).
     */
    static final Identifier NOISE = Identifier.fromNamespaceAndPath(Totality.MOD_ID, "textures/vfx/fire_noise.png");

    /** Elements closer than this (beyond their own visible half-size) to the camera fade out over the next blocks. */
    static final double NEAR_FADE = 3.5;
    /** With the camera inside an explosion's radius, its fire is dimmed down to this fraction at the very centre. */
    static final double INSIDE_MIN = 0.35;

    private static final ByteBufferBuilder ALLOCATOR = new ByteBufferBuilder(RenderType.SMALL_BUFFER_SIZE);
    private static MappableRingBuffer vertices;
    private static final List<FireExplosion> ACTIVE = new ArrayList<>();
    private static final List<Element> FRAME = new ArrayList<>();
    private static final FireExplosion.ElementPool POOL = new FireExplosion.ElementPool();
    private static final Emissive EMISSIVE = new Emissive();
    private static boolean emissiveEnabled = true;
    private static double timeScale = 1.0;

    // ── Development measurement ───────────────────────────────────────────────
    private static TimerQuery timer;
    private static boolean timing;
    private static boolean awaitingTimer;
    private static long gpuSum;
    private static int gpuSamples;
    private static long cpuSum;
    private static int cpuSamples;
    private static int lastElements;
    private static int lastExplosions;
    private static int lastDraws;
    private static int peakElements;
    private static long spawned;

    private FireExplosionRenderer() {}

    public static void register() {
        LevelRenderEvents.BEFORE_TRANSLUCENT_TERRAIN.register(context -> render(context.levelState().cameraRenderState));
        ClientTickEvents.END_CLIENT_TICK.register(client -> {
            if (client.level == null && !ACTIVE.isEmpty()) {
                ACTIVE.clear();
                EmissiveGlow.removeSource(EMISSIVE);
            }
        });
        ClientLifecycleEvents.CLIENT_STOPPING.register(client -> close());
        FireballV2Dev.registerIfDevelopmentEnvironment();
    }

    /**
     * Seconds on the client game clock (game time + partial tick; follows {@code /tick rate}), NaN without a world.
     * Scaled by the development-only slow-motion factor (1 in normal play).
     */
    public static double now() {
        Minecraft mc = Minecraft.getInstance();
        if (mc.level == null) return Double.NaN;
        return (mc.level.getGameTime() + mc.getDeltaTracker().getGameTimeDeltaPartialTick(false)) / 20.0 * timeScale;
    }

    /**
     * Starts an explosion at {@code centre} in {@code level}: walls stop the fire, the ground under the centre (within
     * the radius) gets ground licks. {@code normal} is the hit surface's outward normal (null in the open).
     */
    public static FireExplosion spawn(Level level, Vec3 centre, @Nullable Vec3 normal, double radius, FireExplosionStyle style) {
        double groundY = groundBelow(level, centre, (int) Math.ceil(radius));
        long seed = Double.doubleToLongBits(centre.x * 31.0 + centre.y * 17.0 + centre.z) ^ level.getGameTime() * 0x9E3779B97F4A7C15L;
        FireExplosion e = FireExplosion.create(centre, normal, radius, groundY, seed, style,
                (from, dir, max) -> clearDistance(level, from, dir, max),
                (x, y, z, depth) -> groundBelow(level, new Vec3(x, y, z), depth), now());
        ACTIVE.add(e);
        spawned++;
        return e;
    }

    static double clearDistance(Level level, Vec3 from, Vec3 dir, double max) {
        BlockHitResult hit = level.clip(new ClipContext(from, from.add(dir.scale(max)), ClipContext.Block.COLLIDER,
                ClipContext.Fluid.NONE, CollisionContext.empty()));
        return hit.getType() == HitResult.Type.MISS ? max : hit.getLocation().distanceTo(from);
    }

    /** The top of the first full block at most {@code depth} blocks under {@code at}, or NaN when there is none. */
    static double groundBelow(Level level, Vec3 at, int depth) {
        BlockPos pos = BlockPos.containing(at);
        for (int i = 0; i <= depth; i++) {
            BlockPos p = pos.below(i);
            if (level.getBlockState(p).isCollisionShapeFullBlock(level, p)) return p.getY() + 1.0;
        }
        return Double.NaN;
    }

    private static void render(CameraRenderState camera) {
        Minecraft mc = Minecraft.getInstance();
        double now = now();
        if (timer != null && awaitingTimer && timer.getStatus() == TimerQuery.Status.NOT_RECORDING) {
            gpuSum += timer.get();
            gpuSamples++;
            awaitingTimer = false;
        }
        FireballV2Dev.tickLoop(now);
        ACTIVE.removeIf(e -> Double.isNaN(now) || e.finished(now));
        lastExplosions = ACTIVE.size();
        lastDraws = 0;
        if (ACTIVE.isEmpty() || mc.level == null) {
            lastElements = 0;
            FRAME.clear();
            EmissiveGlow.removeSource(EMISSIVE);
            return;
        }
        long cpuStart = System.nanoTime();
        POOL.reset();
        FRAME.clear();
        for (FireExplosion e : ACTIVE) e.evaluate(now, FRAME, POOL);
        Vec3 cam = camera.pos;
        for (Element el : FRAME) {
            double dx = el.x + el.ax * el.length * 0.5 - cam.x, dy = el.y + el.ay * el.length * 0.5 - cam.y, dz = el.z + el.az * el.length * 0.5 - cam.z;
            el.sortKey = dx * dx + dy * dy + dz * dz;
        }
        FRAME.sort((a, b) -> Double.compare(b.sortKey, a.sortKey));
        lastElements = FRAME.size();
        peakElements = Math.max(peakElements, lastElements);

        Vector3f right = camera.orientation.transform(new Vector3f(1, 0, 0));
        Vector3f up = camera.orientation.transform(new Vector3f(0, 1, 0));
        BufferBuilder buffer = new BufferBuilder(ALLOCATOR, PIPELINE.getPrimitiveTopology(), PIPELINE.getVertexFormatBinding(0));
        for (Element el : FRAME) emit(buffer, el, cam, right, up);
        MeshData mesh = buffer.build();
        cpuSum += System.nanoTime() - cpuStart;
        cpuSamples++;
        if (mesh != null) {
            boolean timed = timing && timer != null && !awaitingTimer && timer.getStatus() == TimerQuery.Status.NOT_RECORDING;
            if (timed) timer.beginProfile();
            draw(mc, mesh, camera.viewRotationMatrix);
            lastDraws = 1;
            if (timed) {
                timer.endProfile();
                awaitingTimer = true;
            }
        }
        if (emissiveEnabled && ACTIVE.stream().anyMatch(e -> e.style().emissive() > 0)) {
            EMISSIVE.frame(right, up);
            EmissiveGlow.addSource(EMISSIVE);
        } else {
            EmissiveGlow.removeSource(EMISSIVE);
        }
    }

    /**
     * Fades an element as the camera gets inside it, and dims a whole explosion while the camera is inside its radius
     * (so standing in the blast tints the view instead of filling it with full-strength fire).
     */
    static float nearFade(Element el, Vec3 cam) {
        double half = el.kind == Kind.BODY || el.kind == Kind.CORE ? el.width * FireExplosion.EDGE : el.width * 0.5;
        double d = Math.sqrt(el.sortKey) - half;
        double fade = Math.clamp(d / NEAR_FADE, 0.0, 1.0);
        double inside = cam.distanceTo(el.owner.centre()) / el.owner.radius();
        if (inside < 1.0) fade *= INSIDE_MIN + (1.0 - INSIDE_MIN) * inside * inside;
        return (float) fade;
    }

    private static void emit(BufferBuilder b, Element el, Vec3 cam, Vector3f right, Vector3f up) {
        float opacity = el.opacity * nearFade(el, cam);
        if (opacity <= 0.003f) return;
        double tex = el.owner.style().texelsPerBlock();
        int r = Math.round(Math.clamp(el.heat / 1.25f, 0.0f, 1.0f) * 255);
        int g = Math.round(Math.clamp(el.erosion, 0.0f, 1.0f) * 255);
        int bl = Math.round(Math.clamp(el.seed, 0.0f, 1.0f) * 255);
        int a = Math.round(Math.clamp(opacity, 0.0f, 1.0f) * 255);
        float x = (float) (el.x - cam.x), y = (float) (el.y - cam.y), z = (float) (el.z - cam.z);
        int kind = el.kind.ordinal();
        if (el.kind == Kind.BODY || el.kind == Kind.CORE) {
            float h = (float) el.width * 0.5f;
            float c = (float) Math.cos(el.angle), s = (float) Math.sin(el.angle);
            // Corner axes in screen coordinates (right, up): the spun square, then stretched along the screen
            // projection of the outward direction (foreshortened: no streak when moving toward the camera).
            float rr = c * h, ru = s * h, ur = -s * h, uu = c * h;
            if (el.kind == Kind.BODY && el.stretch > 1.001f) {
                float pr = (float) (el.ax * right.x() + el.ay * right.y() + el.az * right.z());
                float pu = (float) (el.ax * up.x() + el.ay * up.y() + el.az * up.z());
                float len = (float) Math.sqrt(pr * pr + pu * pu);
                if (len > 1.0e-3f) {
                    float k = (el.stretch - 1.0f) * len;
                    pr /= len;
                    pu /= len;
                    float dr = (rr * pr + ru * pu) * k, du = (ur * pr + uu * pu) * k;
                    rr += dr * pr;
                    ru += dr * pu;
                    ur += du * pr;
                    uu += du * pu;
                    // Pull the centre back along the outward direction so the leading edge does not move.
                    float back = k * h;
                    x -= (float) el.ax * back;
                    y -= (float) el.ay * back;
                    z -= (float) el.az * back;
                }
            }
            float rx = right.x() * rr + up.x() * ru, ry = right.y() * rr + up.y() * ru, rz = right.z() * rr + up.z() * ru;
            float ux = right.x() * ur + up.x() * uu, uy = right.y() * ur + up.y() * uu, uz = right.z() * ur + up.z() * uu;
            int cells = (int) Math.clamp(Math.round(el.width * tex), 6, 60);
            float code = 2.0f * (kind * 16 + 1), v = 2.0f * cells;
            vertex(b, x - rx - ux, y - ry - uy, z - rz - uz, code, v, r, g, bl, a);
            vertex(b, x + rx - ux, y + ry - uy, z + rz - uz, code + 1, v, r, g, bl, a);
            vertex(b, x + rx + ux, y + ry + uy, z + rz + uz, code + 1, v + 1, r, g, bl, a);
            vertex(b, x - rx + ux, y - ry + uy, z - rz + uz, code, v + 1, r, g, bl, a);
            return;
        }
        // Axial billboard (flame tongue along its outward axis, ground lick standing up), turned to face the camera.
        float ax = (float) el.ax, ay = (float) el.ay, az = (float) el.az;
        float len = (float) el.length;
        float mx = x + ax * len * 0.5f, my = y + ay * len * 0.5f, mz = z + az * len * 0.5f;
        float sx = ay * -mz - az * -my, sy = az * -mx - ax * -mz, sz = ax * -my - ay * -mx;
        float sl = (float) Math.sqrt(sx * sx + sy * sy + sz * sz);
        if (sl < 1.0e-4f) {
            sx = right.x();
            sy = right.y();
            sz = right.z();
            sl = 1.0f;
        }
        float hw = (float) el.width * 0.5f / sl;
        sx *= hw;
        sy *= hw;
        sz *= hw;
        int cells = (int) Math.clamp(Math.round(el.width * tex), 4, 40);
        int aspect = (int) Math.clamp(Math.round(len / el.width), 1, 15);
        float code = 2.0f * (kind * 16 + aspect), v = 2.0f * cells;
        float tx = x + ax * len, ty = y + ay * len, tz = z + az * len;
        vertex(b, x - sx, y - sy, z - sz, code, v, r, g, bl, a);
        vertex(b, x + sx, y + sy, z + sz, code + 1, v, r, g, bl, a);
        vertex(b, tx + sx, ty + sy, tz + sz, code + 1, v + 1, r, g, bl, a);
        vertex(b, tx - sx, ty - sy, tz - sz, code, v + 1, r, g, bl, a);
    }

    private static void vertex(BufferBuilder b, float x, float y, float z, float u, float v, int r, int g, int bl, int a) {
        b.addVertex(x, y, z).setUv(u, v).setColor(r, g, bl, a);
    }

    /** Uploads and draws once per frame (a ring-buffer slot must not be reused within a frame on 26.2). */
    @SuppressWarnings("resource")
    private static void draw(Minecraft mc, MeshData mesh, Matrix4f viewMatrix) {
        MeshData.DrawState drawState = mesh.drawState();
        VertexFormat format = drawState.format();
        int size = drawState.vertexCount() * format.getVertexSize();
        if (vertices == null || vertices.size() < size) {
            if (vertices != null) vertices.close();
            vertices = new MappableRingBuffer(() -> "totality fire explosion", GpuBuffer.USAGE_VERTEX | GpuBuffer.USAGE_MAP_WRITE,
                    Math.max(size, 65536));
        }
        try (GpuBufferSlice.MappedView view = vertices.currentBuffer().slice(0, mesh.vertexBuffer().remaining()).map(false, true)) {
            MemoryUtil.memCopy(mesh.vertexBuffer(), view.data());
        }
        RenderSystem.AutoStorageIndexBuffer indexBuffer = RenderSystem.getSequentialBuffer(PIPELINE.getPrimitiveTopology());
        GpuBuffer indices = indexBuffer.getBuffer(drawState.indexCount());
        GpuBufferSlice dynamicTransforms = RenderSystem.getDynamicUniforms().writeTransform(viewMatrix);
        try (RenderPass pass = RenderSystem.getDevice().createCommandEncoder().createRenderPass(() -> "totality fire explosion",
                mc.gameRenderer.mainRenderTarget().getColorTextureView(), Optional.empty(),
                mc.gameRenderer.mainRenderTarget().getDepthTextureView(), OptionalDouble.empty())) {
            pass.setPipeline(PIPELINE);
            RenderSystem.bindDefaultUniforms(pass);
            pass.setUniform("DynamicTransforms", dynamicTransforms);
            pass.bindTexture("Sampler0", mc.getTextureManager().getTexture(NOISE).getTextureView(),
                    RenderSystem.getSamplerCache().getRepeat(FilterMode.LINEAR));
            pass.setVertexBuffer(0, vertices.currentBuffer().slice());
            pass.setIndexBuffer(indices, indexBuffer.type());
            pass.drawIndexed(drawState.indexCount(), 1, 0, 0, 0);
        }
        mesh.close();
        vertices.rotate();
    }

    /**
     * The ignition core (white-gold, a third of its size) and the hottest elements (about 40 % of their size, orange-gold)
     * as emissive quads, so the bloom gives a soft halo without whitening the fire. Its demand (summed weight over
     * {@link FireExplosion#GLOW_PEAK}, at most 1 per explosion) goes to the {@code fireball} budget group. Consumes the frame's
     * elements once.
     */
    private static final class Emissive implements EmissiveSource {
        private final Vector3f right = new Vector3f();
        private final Vector3f up = new Vector3f();
        private final Map<FireExplosion, Float> sums = new IdentityHashMap<>();
        private boolean pending;
        private float demand;

        void frame(Vector3f r, Vector3f u) {
            right.set(r);
            up.set(u);
            pending = true;
            sums.clear();
            for (Element el : FRAME) sums.merge(el.owner, FireExplosion.glowWeight(el), Float::sum);
            demand = 0.0f;
            for (float sum : sums.values()) demand += Math.min(1.0f, sum / FireExplosion.GLOW_PEAK);
        }

        @Override
        public float emissiveDemand() {
            return demand;
        }

        @Override
        public String budgetGroup() {
            return "fireball";
        }

        @Override
        public void emit(EmissiveBuffer buffer, Vec3 camera, float partialTick) {
            if (!pending) return;
            pending = false;
            for (Element el : FRAME) {
                double k = el.owner.style().emissive();
                if (k <= 0) continue;
                float w = (float) (FireExplosion.glowWeight(el) * k * nearFade(el, camera));
                if (w <= 0.003f) continue;
                boolean core = el.kind == Kind.CORE;
                float h = (float) (core ? el.width * 0.33 : el.kind == Kind.TONGUE ? el.width * 0.25 : el.width * 0.2);
                float x = (float) (el.x + el.ax * el.length * 0.5 - camera.x);
                float y = (float) (el.y + el.ay * el.length * 0.5 - camera.y);
                float z = (float) (el.z + el.az * el.length * 0.5 - camera.z);
                float rx = right.x() * h, ry = right.y() * h, rz = right.z() * h;
                float ux = up.x() * h, uy = up.y() * h, uz = up.z() * h;
                buffer.quad(x - rx - ux, y - ry - uy, z - rz - uz, x + rx - ux, y + ry - uy, z + rz - uz,
                        x + rx + ux, y + ry + uy, z + rz + uz, x - rx + ux, y - ry + uy, z - rz + uz,
                        1.0f * w, (core ? 0.8f : 0.45f) * w, (core ? 0.5f : 0.12f) * w, 1.0f);
            }
        }
    }

    // ── Development hooks and measurement ─────────────────────────────────────

    /** Development only: toggles the emissive contribution (to judge the explosion with and without bloom). */
    public static void setEmissiveEnabled(boolean on) {
        emissiveEnabled = on || !VerificationReporter.isDevEnvironment();
    }

    public static boolean emissiveEnabled() {
        return emissiveEnabled;
    }

    public static void clear() {
        ACTIVE.clear();
    }

    /**
     * Development only: plays explosions at {@code scale} × real speed (slow-motion captures of the first tenths of a
     * second). Clears live explosions, whose ages would otherwise jump; always 1 outside a development environment.
     */
    public static void setTimeScale(double scale) {
        ACTIVE.clear();
        timeScale = VerificationReporter.isDevEnvironment() ? scale : 1.0;
    }

    /** The live explosions (read-only; development radius marker). */
    public static List<FireExplosion> active() {
        return Collections.unmodifiableList(ACTIVE);
    }

    public static void setTiming(boolean on) {
        timing = on;
        if (on && timer == null) timer = new TimerQuery();
        resetMeasurements();
    }

    public static void resetMeasurements() {
        gpuSum = gpuSamples = 0;
        cpuSum = cpuSamples = 0;
        peakElements = 0;
    }

    /** Average GPU time of the explosion draw since the last reset, in ms (-1 when nothing was measured). */
    public static double averageGpuMillis() {
        return gpuSamples == 0 ? -1 : gpuSum / 1.0e6 / gpuSamples;
    }

    /** Average CPU time (evaluate + sort + vertex build) per frame since the last reset, in ms. */
    public static double averageCpuMillis() {
        return cpuSamples == 0 ? -1 : cpuSum / 1.0e6 / cpuSamples;
    }

    public static int gpuSamples() {
        return gpuSamples;
    }

    public static int lastElements() {
        return lastElements;
    }

    public static int peakElements() {
        return peakElements;
    }

    public static int lastExplosions() {
        return lastExplosions;
    }

    public static int lastDraws() {
        return lastDraws;
    }

    public static long spawnedTotal() {
        return spawned;
    }

    /** Bytes of the vertex ring buffer currently allocated (3 slots). */
    public static long vertexBufferBytes() {
        return vertices == null ? 0 : 3L * vertices.size();
    }

    public static void close() {
        ALLOCATOR.close();
        if (vertices != null) {
            vertices.close();
            vertices = null;
        }
        if (timer != null) {
            timer.close();
            timer = null;
        }
    }
}
