package zcylas.totality.client.renderer.entity.portal;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.math.Axis;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.entity.EntityRenderer;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.state.EntityRenderState;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.state.level.CameraRenderState;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.resources.Identifier;
import net.minecraft.util.LightCoordsUtil;
import net.minecraft.util.Mth;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import net.minecraft.world.phys.shapes.VoxelShape;
import org.joml.Matrix3f;
import org.joml.Quaternionf;
import org.joml.Vector3f;
import zcylas.totality.Totality;
import zcylas.totality.entity.portal.VisualPortalEntity;
import zcylas.totality.entity.portal.VisualPortalVfx;

/**
 * Draws the visual portal test (after Context/References/Other/Totality_ Green Portal Reference Sheet.png) as the
 * reference's composited layers, all at 16 texels a block and full-bright:
 * <ul>
 *   <li>core: the opaque swirl surface, 16 frames looping every 1.6 s (arms flowing in and around). It is drawn with
 *       vanilla's dissolve cutout, so the opening fills it in pixel by pixel from the centre out and the collapse
 *       takes it away from the rim in (the mask's alpha orders the pixels);</li>
 *   <li>glow: the ragged, flickering rim, a stepped halo, loose flecks and spark highlights riding the arms inward;</li>
 *   <li>edge: a thin glowing band round the oval, so the portal reads as a sliver of light edge-on;</li>
 *   <li>ground: a green light pool under an upright portal standing near the ground.</li>
 * </ul>
 * Both faces show the swirl: the layers are turned to the side the camera is on (from behind, the surface is seen
 * mirrored, as a thin sheet would be). Textures: textures/entity/visual_portal/, generated by
 * Totality-Research/visual-portal/tools/portal_textures.py.
 */
public class VisualPortalRenderer extends EntityRenderer<VisualPortalEntity, VisualPortalRenderer.State> {

    private static final RenderType CORE = RenderTypes.entityCutoutDissolve(texture("core"), texture("core_mask"));
    private static final RenderType GLOW = RenderTypes.eyes(texture("glow"));
    private static final RenderType EDGE = RenderTypes.eyes(texture("edge"));
    private static final RenderType GROUND = RenderTypes.eyes(texture("ground"));

    private static final int FRAMES = 16;
    private static final int TICKS_PER_FRAME = 2;
    /** Half the 40 x 56 texel frame, in blocks (the oval inside it is 26 x 38 texels). */
    private static final float QUAD_HALF_WIDTH = 20.0F / 16.0F;
    private static final float QUAD_HALF_HEIGHT = 28.0F / 16.0F;
    /** Half the thickness of the edge band. */
    private static final float EDGE_DEPTH = 0.04F;
    private static final int EDGE_SEGMENTS = 48;
    /** How far below the oval's bottom the ground may be for the light pool to show. */
    private static final float GROUND_REACH = 1.5F;

    public static class State extends EntityRenderState {
        VisualPortalEntity.Phase phase = VisualPortalEntity.Phase.STABLE;
        float phaseTime;
        float size = 1.0F;
        final Quaternionf rotation = new Quaternionf();
        final Vector3f right = new Vector3f(1, 0, 0);
        final Vector3f normal = new Vector3f(0, 0, 1);
        /** The ground's height under the portal, or NaN when there is no pool to draw. */
        float groundY = Float.NaN;
        float groundDrop;
    }

    public VisualPortalRenderer(EntityRendererProvider.Context ctx) {
        super(ctx);
    }

    private static Identifier texture(String name) {
        return Identifier.fromNamespaceAndPath(Totality.MOD_ID, "textures/entity/visual_portal/" + name + ".png");
    }

    @Override
    public State createRenderState() {
        return new State();
    }

    @Override
    public void extractRenderState(VisualPortalEntity entity, State state, float partialTicks) {
        super.extractRenderState(entity, state, partialTicks);
        state.phase = entity.phase();
        state.phaseTime = entity.phaseAge() + partialTicks;
        state.size = entity.size();
        Vec3[] axes = VisualPortalEntity.basis(entity.getYRot(), entity.getXRot());
        state.right.set((float) axes[0].x, (float) axes[0].y, (float) axes[0].z);
        state.normal.set((float) axes[2].x, (float) axes[2].y, (float) axes[2].z);
        Matrix3f m = new Matrix3f(state.right, new Vector3f((float) axes[1].x, (float) axes[1].y, (float) axes[1].z), state.normal);
        state.rotation.setFromNormalized(m);
        state.groundY = Float.NaN;
        if (Math.abs(axes[2].y) < 0.5) findGround(entity.level(), state, entity.position(), (float) (axes[1].y * VisualPortalVfx.HALF_HEIGHT * state.size));
    }

    /** The first surface within reach below the bottom of an upright portal. */
    private static void findGround(Level level, State state, Vec3 centre, float halfHeight) {
        double bottom = centre.y - halfHeight;
        BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos(centre.x, bottom + 0.3, centre.z);
        for (int i = 0; i < 3; i++, pos.move(0, -1, 0)) {
            VoxelShape shape = level.getBlockState(pos).getCollisionShape(level, pos);
            if (shape.isEmpty()) continue;
            double top = pos.getY() + shape.max(Direction.Axis.Y);
            double drop = bottom - top;
            if (drop > -0.4 && drop < GROUND_REACH) {
                state.groundY = (float) top;
                state.groundDrop = (float) Math.max(0.0, drop);
            }
            return;
        }
    }

    @Override
    protected AABB getBoundingBoxForCulling(VisualPortalEntity entity) {
        float reach = 2.4F * entity.size();
        return AABB.ofSize(entity.position(), reach * 2, reach * 2, reach * 2);
    }

    @Override
    public void submit(State state, PoseStack poseStack, SubmitNodeCollector collector, CameraRenderState camera) {
        // The phase animation: (width, height) scale, how much of the surface is dissolved in, the glow's opacity, and
        // extra swirl ticks (it spins up while opening and races while collapsing; continuous across the phases).
        float sx = 1, sy = 1, surface = 1, glow = 1, spin = 16;
        switch (state.phase) {
            case OPENING -> {
                float p = Math.min(1.0F, state.phaseTime / VisualPortalEntity.OPEN_TICKS);
                sy = easeOutBack(clamp01(p / 0.55F));                       // it tears open upright, then widens
                sx = easeOutBack(clamp01((p - 0.1F) / 0.55F));
                surface = smoothstep(0.05F, 0.8F, p);
                glow = clamp01(p * 4.0F);
                spin = 16.0F * p * (2.0F - p);
            }
            case COLLAPSING -> {
                float q = Math.min(1.0F, state.phaseTime / VisualPortalEntity.COLLAPSE_TICKS);
                float breakAt = (float) VisualPortalVfx.BREAK_TICK / VisualPortalEntity.COLLAPSE_TICKS;
                float k = clamp01((q - 0.15F) / (breakAt - 0.15F));
                float s = q < 0.15F
                        ? 1.0F + 0.07F * Mth.sin(q / 0.15F * Mth.HALF_PI)       // a last swell
                        : 1.07F * (1.0F - k * k);
                sx = (float) Math.pow(s, 1.6);                                // it narrows to a slit and snaps shut
                sy = (float) Math.pow(s, 0.7);
                surface = 1.0F - smoothstep(0.35F, breakAt, q);               // the surface frays from the rim as it shrinks
                glow = 1.0F - smoothstep(breakAt - 0.15F, breakAt, q);
                spin = 16.0F + 40.0F * q * q;
            }
            case STABLE -> { }
        }
        if (sx > 0.01F && sy > 0.01F && glow > 0.0F) {
            int frame = Math.floorMod((int) ((state.ageInTicks + spin) / TICKS_PER_FRAME), FRAMES);
            float v0 = (float) frame / FRAMES, v1 = (float) (frame + 1) / FRAMES;
            float hw = QUAD_HALF_WIDTH * sx, hh = QUAD_HALF_HEIGHT * sy;
            poseStack.pushPose();
            poseStack.mulPose(state.rotation);
            poseStack.scale(state.size, state.size, state.size);
            Vec3 toCamera = camera.pos.subtract(state.x, state.y, state.z);
            double facing = (toCamera.x * state.normal.x + toCamera.y * state.normal.y + toCamera.z * state.normal.z) / Math.max(1.0E-4, toCamera.length());
            if (facing < 0) {
                poseStack.mulPose(Axis.YP.rotationDegrees(180.0F));          // turn the layers to the camera's side
            }
            int surfaceAlpha = Math.round(surface * 255);
            if (surfaceAlpha > 0) {
                collector.submitCustomGeometry(poseStack, CORE, (pose, buffer) -> quad(buffer, pose, hw, hh, 0.0F, v0, v1, surfaceAlpha));
            }
            int glowAlpha = Math.round(glow * 255);
            collector.submitCustomGeometry(poseStack, GLOW, (pose, buffer) -> quad(buffer, pose, hw, hh, 0.015F, v0, v1, glowAlpha));
            // The edge band only shows at grazing angles (face-on its near side would draw a smooth line over the pixel rim).
            int edgeAlpha = Math.round(glowAlpha * (1.0F - smoothstep(0.25F, 0.5F, (float) Math.abs(facing))));
            if (edgeAlpha > 0) {
                float ew = VisualPortalVfx.HALF_WIDTH * 0.97F * sx, eh = VisualPortalVfx.HALF_HEIGHT * 0.97F * sy;
                collector.submitCustomGeometry(poseStack, EDGE, (pose, buffer) -> edgeBand(buffer, pose, ew, eh, edgeAlpha));
            }
            poseStack.popPose();
            if (!Float.isNaN(state.groundY)) submitGround(state, poseStack, collector, sx, glow * surface);
        }
        super.submit(state, poseStack, collector, camera);
    }

    /** The light pool: an ellipse on the ground, long along the portal's width, fading as the portal hovers higher. */
    private static void submitGround(State state, PoseStack poseStack, SubmitNodeCollector collector, float sx, float strength) {
        int alpha = Math.round(255 * strength * clamp01(1.0F - state.groundDrop / GROUND_REACH));
        if (alpha <= 0) return;
        Vector3f r = new Vector3f(state.right.x, 0, state.right.z).normalize().mul(1.35F * state.size * Math.max(sx, 0.2F));
        Vector3f f = new Vector3f(state.normal.x, 0, state.normal.z).normalize().mul(0.7F * state.size);
        float y = state.groundY + 0.015F - (float) state.y;
        collector.submitCustomGeometry(poseStack, GROUND, (pose, buffer) -> {
            // both windings: one of them faces up (the other is culled)
            vertex(buffer, pose, -r.x - f.x, y, -r.z - f.z, 0, 1, alpha);
            vertex(buffer, pose, r.x - f.x, y, r.z - f.z, 1, 1, alpha);
            vertex(buffer, pose, r.x + f.x, y, r.z + f.z, 1, 0, alpha);
            vertex(buffer, pose, -r.x + f.x, y, -r.z + f.z, 0, 0, alpha);
            vertex(buffer, pose, -r.x + f.x, y, -r.z + f.z, 0, 0, alpha);
            vertex(buffer, pose, r.x + f.x, y, r.z + f.z, 1, 0, alpha);
            vertex(buffer, pose, r.x - f.x, y, r.z - f.z, 1, 1, alpha);
            vertex(buffer, pose, -r.x - f.x, y, -r.z - f.z, 0, 1, alpha);
        });
    }

    /** A thin band round the oval (both windings, so its near side shows from any angle). */
    private static void edgeBand(VertexConsumer buffer, PoseStack.Pose pose, float a, float b, int alpha) {
        for (int i = 0; i < EDGE_SEGMENTS; i++) {
            float t0 = Mth.TWO_PI * i / EDGE_SEGMENTS, t1 = Mth.TWO_PI * (i + 1) / EDGE_SEGMENTS;
            float x0 = a * Mth.cos(t0), y0 = b * Mth.sin(t0), x1 = a * Mth.cos(t1), y1 = b * Mth.sin(t1);
            float u0 = (float) i / EDGE_SEGMENTS, u1 = (float) (i + 1) / EDGE_SEGMENTS;
            vertex(buffer, pose, x0, y0, -EDGE_DEPTH, u0, 1, alpha);
            vertex(buffer, pose, x1, y1, -EDGE_DEPTH, u1, 1, alpha);
            vertex(buffer, pose, x1, y1, EDGE_DEPTH, u1, 0, alpha);
            vertex(buffer, pose, x0, y0, EDGE_DEPTH, u0, 0, alpha);
            vertex(buffer, pose, x0, y0, EDGE_DEPTH, u0, 0, alpha);
            vertex(buffer, pose, x1, y1, EDGE_DEPTH, u1, 0, alpha);
            vertex(buffer, pose, x1, y1, -EDGE_DEPTH, u1, 1, alpha);
            vertex(buffer, pose, x0, y0, -EDGE_DEPTH, u0, 1, alpha);
        }
    }

    /** A frame-sized quad facing +z (the camera's side) at depth {@code z}; v0..v1 selects the animation frame. */
    private static void quad(VertexConsumer buffer, PoseStack.Pose pose, float hw, float hh, float z, float v0, float v1, int alpha) {
        vertex(buffer, pose, -hw, -hh, z, 0, v1, alpha);
        vertex(buffer, pose, hw, -hh, z, 1, v1, alpha);
        vertex(buffer, pose, hw, hh, z, 1, v0, alpha);
        vertex(buffer, pose, -hw, hh, z, 0, v0, alpha);
    }

    private static void vertex(VertexConsumer buffer, PoseStack.Pose pose, float x, float y, float z, float u, float v, int alpha) {
        buffer.addVertex(pose, x, y, z)
                .setColor(255, 255, 255, alpha)
                .setUv(u, v)
                .setOverlay(OverlayTexture.NO_OVERLAY)
                .setLight(LightCoordsUtil.FULL_BRIGHT)
                .setNormal(0.0F, 1.0F, 0.0F);   // world up, untransformed: the lit side, whatever the portal's angle
    }

    private static float clamp01(float v) {
        return Math.clamp(v, 0.0F, 1.0F);
    }

    private static float smoothstep(float e0, float e1, float x) {
        float t = clamp01((x - e0) / (e1 - e0));
        return t * t * (3 - 2 * t);
    }

    private static float cube(float t) {
        return t * t * t;
    }

    private static float easeOutBack(float t) {
        float c1 = 1.70158F, c3 = c1 + 1;
        return 1 + c3 * cube(t - 1) + c1 * (t - 1) * (t - 1);
    }
}
