package zcylas.totality.client.renderer.entity.magic;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.math.Axis;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.entity.EntityRenderer;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.state.EntityRenderState;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.state.level.CameraRenderState;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.Identifier;
import net.minecraft.util.LightCoordsUtil;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import org.joml.Quaternionf;
import org.joml.Vector3f;
import zcylas.totality.Totality;
import zcylas.totality.entity.magic.FireballProjectileEntity;
import zcylas.totality.entity.magic.FireballVfx;

/**
 * Renderer for {@link FireballProjectileEntity}: D&D's "bright streak" — a small, intense manifestation of magic
 * (Context/References/Other/fireball.png), all full-bright and animated over 4 frames at 20 fps (built like the Firebolt
 * projectile; head and streak after the reference's MAIN PROJECTILE and TRAVEL VIEW):
 * <ul>
 *   <li>the comet body: a quad along the direction of travel, turned about that axis to face the camera — a hot yellow
 *       spine with orange and red flanks breaking into blocky chunks toward its end, never white; its rounded front is
 *       tucked under the head; it grows from the cast point to 3.2 blocks;</li>
 *   <li>the head: a compact round fire ball with a blocky red-orange rim and its white-hot spot set back from the
 *       front, turned so its short tongues trail along the on-screen flight line;</li>
 *   <li>the hot rear bloom: a small stepped white-yellow flare just behind and below the head's centre, inside a
 *       stepped amber/orange/red halo — never the front face of the projectile.</li>
 * </ul>
 * All of it materializes over the first 2.5 blocks and is only drawn once 1.2 blocks from the cast point, clear of
 * the caster's head.
 * <p>Textures: textures/entity/fireball/{tail,core,bloom,halo}.png, generated by
 * Totality-Research/fireball-correction/tools/fireball_textures.py.
 * <p>Fireball V2 (VFX Experiment 3, B3): the projectile is drawn by {@code FireballProjectileVfx} (bead and streak).
 * This V1 look is kept only as a development comparison and draws nothing unless
 * {@link FireballVfx#setLegacyProjectile} is on (development environment only).
 */
public class FireballProjectileRenderer extends EntityRenderer<FireballProjectileEntity, FireballProjectileRenderer.State> {

    private static final RenderType TAIL = RenderTypes.entityTranslucentEmissive(texture("tail"));
    private static final RenderType CORE = RenderTypes.entityTranslucentEmissive(texture("core"));
    private static final RenderType HALO = RenderTypes.entityTranslucentEmissive(texture("halo"));
    private static final RenderType BLOOM = RenderTypes.entityTranslucentEmissive(texture("bloom"));

    /**
     * Sizes in blocks, after the reference's MAIN PROJECTILE / TRAVEL VIEW: a compact round fire head and a comet body
     * about as wide as the head behind it, so head and streak read as one teardrop.
     */
    private static final float CORE_SIZE = 0.75F;
    private static final float BLOOM_SIZE = 0.55F;
    private static final float HALO_SIZE = 1.4F;
    /** The rear bloom sits this far behind the head's centre along the flight path, and this far below it. */
    private static final float BLOOM_BACK = 0.16F;
    private static final float BLOOM_DOWN = 0.05F;
    private static final float TAIL_LENGTH = 3.2F;
    private static final float TAIL_WIDTH = 0.8F;
    /**
     * The streak's front: this fraction of its length lies in front of the head's centre. Its rounded front ends
     * inside the head (0.1 blocks ahead of the centre), never poking out in front of it as a flat slab.
     */
    private static final float TAIL_HEAD = 0.1F / TAIL_LENGTH;
    /** Not drawn until it is clear of the caster's head (at the cast point it would fill a first-person view). */
    private static final float SHOW_AFTER = 1.2F;

    public static class State extends EntityRenderState {
        final Vector3f dir = new Vector3f(0, 0, 1);
        float traveled;
    }

    public FireballProjectileRenderer(EntityRendererProvider.Context ctx) {
        super(ctx);
    }

    private static Identifier texture(String name) {
        return Identifier.fromNamespaceAndPath(Totality.MOD_ID, "textures/entity/fireball/" + name + ".png");
    }

    @Override
    public State createRenderState() {
        return new State();
    }

    @Override
    public void extractRenderState(FireballProjectileEntity entity, State state, float partialTicks) {
        super.extractRenderState(entity, state, partialTicks);
        Vec3 v = entity.getDeltaMovement();
        if (v.lengthSqr() < 1.0E-8) v = Vec3.directionFromRotation(entity.getXRot(), entity.getYRot());
        v = v.normalize();
        state.dir.set((float) v.x, (float) v.y, (float) v.z);
        Vec3 origin = entity.visualOrigin();
        state.traveled = origin == null ? 0.0F : (float) new Vec3(state.x, state.y, state.z).distanceTo(origin);
    }

    /** The streak reaches up to 3 blocks behind the orb: keep drawing it while only the streak is on screen. */
    @Override
    protected AABB getBoundingBoxForCulling(FireballProjectileEntity entity) {
        return super.getBoundingBoxForCulling(entity).inflate(TAIL_LENGTH);
    }

    @Override
    public void submit(State state, PoseStack poseStack, SubmitNodeCollector collector, CameraRenderState camera) {
        if (FireballVfx.legacyProjectile() && state.traveled >= SHOW_AFTER) {
            int frame = ((int) state.ageInTicks) & 3;
            submitTail(state, poseStack, collector, camera, frame);
            float u0 = frame / 4.0F, u1 = (frame + 1) / 4.0F;
            float grow = 0.45F + 0.55F * Math.min(1.0F, state.traveled / 2.5F);
            // The hot rear bloom (and the halo round it): behind and a little below the core, and pushed back in view
            // depth so the core always draws over it, whichever way the fireball flies relative to the camera.
            poseStack.pushPose();
            poseStack.translate(-state.dir.x * BLOOM_BACK, -state.dir.y * BLOOM_BACK - BLOOM_DOWN, -state.dir.z * BLOOM_BACK);
            poseStack.mulPose(camera.orientation);
            collector.submitCustomGeometry(poseStack, HALO, (pose, buffer) -> quad(buffer, pose, grow * HALO_SIZE / 2, -0.3F, 0, 1, 0, 1));
            collector.submitCustomGeometry(poseStack, BLOOM, (pose, buffer) -> quad(buffer, pose, grow * BLOOM_SIZE / 2, -0.25F, 0, 1, 0, 1));
            poseStack.popPose();
            // The leading core, turned about the view axis so its flame tongues (the texture's +x side) trail behind it
            // along the on-screen flight line, and its bright dome (-x) leads.
            poseStack.pushPose();
            poseStack.mulPose(camera.orientation);
            Vector3f onScreen = new Quaternionf(camera.orientation).conjugate().transform(new Vector3f(state.dir));
            poseStack.mulPose(Axis.ZP.rotation((float) Math.atan2(-onScreen.y, -onScreen.x)));
            collector.submitCustomGeometry(poseStack, CORE, (pose, buffer) -> quad(buffer, pose, grow * CORE_SIZE / 2, 0.04F, u0, u1, 0, 1));
            poseStack.popPose();
        }
        super.submit(state, poseStack, collector, camera);
    }

    /** The streak lies along the travel direction and is turned about it to face the camera (an axial billboard). */
    private static void submitTail(State state, PoseStack poseStack, SubmitNodeCollector collector, CameraRenderState camera, int frame) {
        float length = Math.min(TAIL_LENGTH, state.traveled / (1 - TAIL_HEAD));
        if (length < 0.3F) return;
        Vector3f dir = new Vector3f(state.dir);
        Vector3f toCamera = new Vector3f((float) (camera.pos.x - state.x), (float) (camera.pos.y - state.y), (float) (camera.pos.z - state.z));
        Vector3f side = new Vector3f(dir).cross(toCamera);
        if (side.lengthSquared() < 1.0E-6F) return;
        side.normalize().mul(TAIL_WIDTH / 2);
        Vector3f front = new Vector3f(dir).mul(length * TAIL_HEAD);
        Vector3f back = new Vector3f(dir).mul(-length * (1 - TAIL_HEAD));
        float v0 = frame / 4.0F, v1 = (frame + 1) / 4.0F;
        collector.submitCustomGeometry(poseStack, TAIL, (pose, buffer) -> {
            vertex(buffer, pose, back.x - side.x, back.y - side.y, back.z - side.z, 0, v1);
            vertex(buffer, pose, front.x - side.x, front.y - side.y, front.z - side.z, 1, v1);
            vertex(buffer, pose, front.x + side.x, front.y + side.y, front.z + side.z, 1, v0);
            vertex(buffer, pose, back.x + side.x, back.y + side.y, back.z + side.z, 0, v0);
            vertex(buffer, pose, back.x + side.x, back.y + side.y, back.z + side.z, 0, v0);
            vertex(buffer, pose, front.x + side.x, front.y + side.y, front.z + side.z, 1, v0);
            vertex(buffer, pose, front.x - side.x, front.y - side.y, front.z - side.z, 1, v1);
            vertex(buffer, pose, back.x - side.x, back.y - side.y, back.z - side.z, 0, v1);
        });
    }

    /** A camera-facing square of half-size {@code h} at depth {@code z} (toward the camera is +z). */
    private static void quad(VertexConsumer buffer, PoseStack.Pose pose, float h, float z, float u0, float u1, float v0, float v1) {
        vertex(buffer, pose, -h, -h, z, u0, v1);
        vertex(buffer, pose, h, -h, z, u1, v1);
        vertex(buffer, pose, h, h, z, u1, v0);
        vertex(buffer, pose, -h, h, z, u0, v0);
    }

    private static void vertex(VertexConsumer buffer, PoseStack.Pose pose, float x, float y, float z, float u, float v) {
        buffer.addVertex(pose, x, y, z)
                .setColor(-1)
                .setUv(u, v)
                .setOverlay(OverlayTexture.NO_OVERLAY)
                .setLight(LightCoordsUtil.FULL_BRIGHT)
                .setNormal(pose, 0.0F, 1.0F, 0.0F);
    }
}
