package zcylas.totality.client.renderer.entity.magic;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.entity.EntityRenderer;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.state.EntityRenderState;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.state.level.CameraRenderState;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.Identifier;
import net.minecraft.util.LightCoordsUtil;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import org.joml.Vector3f;
import zcylas.totality.Totality;
import zcylas.totality.entity.magic.SpellBoltEntity;

/**
 * Renderer for {@link SpellBoltEntity}. Most bolt spells draw nothing here (their dust trail comes from the entity's
 * tick). A Firebolt ({@link SpellBoltEntity.VisualStyle#FIREBOLT}) is drawn as a pixel-art fire projectile after
 * Context/References/Other/firebolt_reference.png, all full-bright and animated at 20 frames a second over 4 frames:
 * <ul>
 *   <li>a flame tail: a quad lying along the direction of travel and turned to face the camera around that axis, so
 *       the flames always stream straight back behind the core, from any view; it grows from the cast point (so it
 *       never reaches back into the caster's face) to 2.6 blocks at full speed;</li>
 *   <li>the core: a camera-facing white-hot ball over the tail's head, growing to full size over its first 2 blocks;</li>
 *   <li>a stepped halo behind the core.</li>
 * </ul>
 * Textures: textures/entity/firebolt/{tail,core,halo}.png, generated by
 * Totality-Research/firebolt-vfx/tools/firebolt_textures.py.
 */
public class SpellBoltRenderer extends EntityRenderer<SpellBoltEntity, SpellBoltRenderer.State> {

    private static final RenderType TAIL = RenderTypes.entityTranslucentEmissive(texture("tail"));
    private static final RenderType CORE = RenderTypes.entityTranslucentEmissive(texture("core"));
    private static final RenderType HALO = RenderTypes.entityTranslucentEmissive(texture("halo"));

    /** Sizes in blocks (1 texel = 1/16 block for the core and halo; the tail is stretched for the 2.5 b/t speed). */
    private static final float CORE_SIZE = 1.0F;
    private static final float HALO_SIZE = 2.0F;
    private static final float TAIL_LENGTH = 2.6F;
    private static final float TAIL_WIDTH = 1.0F;
    /** The tail texture's head: this fraction of its length lies in front of the bolt's centre (under the core). */
    private static final float TAIL_HEAD = 6.0F / 32.0F;

    public static class State extends EntityRenderState {
        boolean firebolt;
        final Vector3f dir = new Vector3f(0, 0, 1);
        float traveled;
    }

    public SpellBoltRenderer(EntityRendererProvider.Context ctx) {
        super(ctx);
    }

    private static Identifier texture(String name) {
        return Identifier.fromNamespaceAndPath(Totality.MOD_ID, "textures/entity/firebolt/" + name + ".png");
    }

    @Override
    public State createRenderState() {
        return new State();
    }

    @Override
    public void extractRenderState(SpellBoltEntity entity, State state, float partialTicks) {
        super.extractRenderState(entity, state, partialTicks);
        state.firebolt = entity.visualStyle() == SpellBoltEntity.VisualStyle.FIREBOLT;
        if (!state.firebolt) return;
        Vec3 v = entity.getDeltaMovement();
        if (v.lengthSqr() < 1.0E-8) v = Vec3.directionFromRotation(entity.getXRot(), entity.getYRot());
        v = v.normalize();
        state.dir.set((float) v.x, (float) v.y, (float) v.z);
        Vec3 origin = entity.visualOrigin();
        state.traveled = origin == null ? 0.0F : (float) new Vec3(state.x, state.y, state.z).distanceTo(origin);
    }

    /** The flame tail reaches up to 2.6 blocks behind the bolt: keep drawing it while only the tail is on screen. */
    @Override
    protected AABB getBoundingBoxForCulling(SpellBoltEntity entity) {
        return entity.visualStyle() == SpellBoltEntity.VisualStyle.FIREBOLT
                ? super.getBoundingBoxForCulling(entity).inflate(TAIL_LENGTH)
                : super.getBoundingBoxForCulling(entity);
    }

    @Override
    public void submit(State state, PoseStack poseStack, SubmitNodeCollector collector, CameraRenderState camera) {
        if (state.firebolt) {
            int frame = ((int) state.ageInTicks) & 3;
            submitTail(state, poseStack, collector, camera, frame);
            // Camera-facing sprites: the halo just behind the centre, the core just in front of it.
            poseStack.pushPose();
            poseStack.mulPose(camera.orientation);
            float u0 = frame / 4.0F, u1 = (frame + 1) / 4.0F;
            // The core materializes: 55% of its size at the cast point, full size after 2 blocks.
            float grow = 0.55F + 0.45F * Math.min(1.0F, state.traveled / 2.0F);
            collector.submitCustomGeometry(poseStack, HALO, (pose, buffer) -> quad(buffer, pose, grow * HALO_SIZE / 2, -0.04F, 0, 1, 0, 1));
            collector.submitCustomGeometry(poseStack, CORE, (pose, buffer) -> quad(buffer, pose, grow * CORE_SIZE / 2, 0.04F, u0, u1, 0, 1));
            poseStack.popPose();
        }
        super.submit(state, poseStack, collector, camera);
    }

    /**
     * The tail quad lies along the travel direction and is turned about it to face the camera (an axial billboard).
     * Seen head-on it collapses to a sliver hidden by the core, which is what a bolt flying at the camera looks like.
     */
    private static void submitTail(State state, PoseStack poseStack, SubmitNodeCollector collector, CameraRenderState camera, int frame) {
        // The tail's back end never reaches behind the cast point (so it never trails into the caster's view).
        float length = Math.min(TAIL_LENGTH, state.traveled / (1 - TAIL_HEAD));
        if (length < 0.3F) return;
        Vector3f dir = new Vector3f(state.dir);
        Vector3f toCamera = new Vector3f((float) (camera.pos.x - state.x), (float) (camera.pos.y - state.y), (float) (camera.pos.z - state.z));
        Vector3f side = new Vector3f(dir).cross(toCamera);
        if (side.lengthSquared() < 1.0E-6F) return;
        side.normalize().mul(TAIL_WIDTH / 2);
        Vector3f front = new Vector3f(dir).mul(length * TAIL_HEAD);
        Vector3f back = new Vector3f(dir).mul(-length * (1 - TAIL_HEAD));
        float v0 = frame / 4.0F, v1 = (frame + 1) / 4.0F;
        collector.submitCustomGeometry(poseStack, TAIL, (pose, buffer) -> {
            // u: 0 at the tail end, 1 at the head; drawn from both sides (no back-face culling surprises).
            vertex(buffer, pose, back.x - side.x, back.y - side.y, back.z - side.z, 0, v1);
            vertex(buffer, pose, front.x - side.x, front.y - side.y, front.z - side.z, 1, v1);
            vertex(buffer, pose, front.x + side.x, front.y + side.y, front.z + side.z, 1, v0);
            vertex(buffer, pose, back.x + side.x, back.y + side.y, back.z + side.z, 0, v0);
            vertex(buffer, pose, back.x + side.x, back.y + side.y, back.z + side.z, 0, v0);
            vertex(buffer, pose, front.x + side.x, front.y + side.y, front.z + side.z, 1, v0);
            vertex(buffer, pose, front.x - side.x, front.y - side.y, front.z - side.z, 1, v1);
            vertex(buffer, pose, back.x - side.x, back.y - side.y, back.z - side.z, 0, v1);
        });
    }

    /** A camera-facing square of half-size {@code h} at depth {@code z} (toward the camera is +z). */
    private static void quad(VertexConsumer buffer, PoseStack.Pose pose, float h, float z, float u0, float u1, float v0, float v1) {
        vertex(buffer, pose, -h, -h, z, u0, v1);
        vertex(buffer, pose, h, -h, z, u1, v1);
        vertex(buffer, pose, h, h, z, u1, v0);
        vertex(buffer, pose, -h, h, z, u0, v0);
    }

    private static void vertex(VertexConsumer buffer, PoseStack.Pose pose, float x, float y, float z, float u, float v) {
        buffer.addVertex(pose, x, y, z)
                .setColor(-1)
                .setUv(u, v)
                .setOverlay(OverlayTexture.NO_OVERLAY)
                .setLight(LightCoordsUtil.FULL_BRIGHT)
                .setNormal(pose, 0.0F, 1.0F, 0.0F);
    }
}
