package zcylas.totality.client.photo;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.util.Locale;
import java.util.regex.Pattern;

/**
 * Everything the Gallery knows about one photograph, stored as {@code photos/<id>.json} next to {@code <id>.<format>}.
 *
 * <p>The {@link #id} is stable and never shown or edited: renaming changes only {@link #name}. Future features add
 * fields here (albums, export history) or put loosely-coupled data in {@link #extra} (e.g. a Codex discovery id from
 * Scan mode — a reference only, the discovery itself lives elsewhere and never depends on this file).
 *
 * @param number    sequence number in this gallery at capture time (gives default names "Photo N")
 * @param format    image file format; V1 always writes lossless "png"
 * @param mode      camera mode id ("normal"; "scan" later)
 * @param capture   "clean" (world only) or "full_screen" (development capture including HUD and overlays)
 * @param dimension dimension id where it was taken; x/y/z/yaw/pitch are the camera's position and facing
 */
public record PhotoMetadata(String id, int number, String name, long capturedAt, String format, int width, int height,
                            boolean favorite, String mode, float zoom, float fov, String capture,
                            String dimension, double x, double y, double z, float yaw, float pitch, JsonObject extra) {

    public static final int SCHEMA = 1;
    public static final int MAX_NAME_LENGTH = 40;
    private static final Pattern ID = Pattern.compile("[0-9]{8}-[0-9]{6}-[0-9]{3}-[0-9a-f]{4}");
    private static final Pattern FORMAT = Pattern.compile("png|jpg");

    public PhotoMetadata {
        if (!isValidId(id)) throw new IllegalArgumentException("invalid photo id: " + id);
        if (!FORMAT.matcher(format).matches()) throw new IllegalArgumentException("unsupported format: " + format);
        name = cleanName(name);
        if (name.isEmpty()) name = defaultName(number);
        extra = extra == null ? new JsonObject() : extra.deepCopy();
    }

    /** Ids are generated by {@link GalleryStore#newId} and are also safe file names (no separators, no dots). */
    public static boolean isValidId(String id) {
        return id != null && ID.matcher(id).matches();
    }

    public static String defaultName(int number) {
        return number > 0 ? "Photo " + number : "Photo";
    }

    /** Trims, removes control characters, Unicode format characters and Minecraft formatting codes, caps the length. */
    public static String cleanName(String raw) {
        if (raw == null) return "";
        StringBuilder b = new StringBuilder();
        raw.replaceAll("§.?", "").strip().codePoints().filter(c -> !Character.isISOControl(c)
                && Character.getType(c) != Character.FORMAT).forEach(b::appendCodePoint);
        String s = b.toString().strip();
        return s.length() > MAX_NAME_LENGTH ? s.substring(0, MAX_NAME_LENGTH).strip() : s;
    }

    public String fileName() {
        return id + "." + format;
    }

    public PhotoMetadata withName(String newName) {
        return new PhotoMetadata(id, number, newName, capturedAt, format, width, height, favorite, mode, zoom, fov, capture,
                dimension, x, y, z, yaw, pitch, extra);
    }

    public PhotoMetadata withFavorite(boolean fav) {
        return new PhotoMetadata(id, number, name, capturedAt, format, width, height, fav, mode, zoom, fov, capture,
                dimension, x, y, z, yaw, pitch, extra);
    }

    public PhotoMetadata withSize(int w, int h) {
        return new PhotoMetadata(id, number, name, capturedAt, format, w, h, favorite, mode, zoom, fov, capture,
                dimension, x, y, z, yaw, pitch, extra);
    }

    public JsonObject toJson() {
        JsonObject o = new JsonObject();
        o.addProperty("schema", SCHEMA);
        o.addProperty("id", id);
        o.addProperty("number", number);
        o.addProperty("name", name);
        o.addProperty("capturedAt", capturedAt);
        o.addProperty("format", format);
        o.addProperty("width", width);
        o.addProperty("height", height);
        o.addProperty("favorite", favorite);
        o.addProperty("mode", mode);
        o.addProperty("zoom", zoom);
        o.addProperty("fov", fov);
        o.addProperty("capture", capture);
        o.addProperty("dimension", dimension);
        JsonObject pos = new JsonObject();
        pos.addProperty("x", x);
        pos.addProperty("y", y);
        pos.addProperty("z", z);
        pos.addProperty("yaw", yaw);
        pos.addProperty("pitch", pitch);
        o.add("position", pos);
        o.add("extra", extra.deepCopy());
        return o;
    }

    /**
     * Parses a sidecar. Unknown fields are ignored; missing optional fields get defaults; the id must match
     * {@code expectedId} (the file's own name), so a copied or edited sidecar can never point at another photo.
     */
    public static PhotoMetadata fromJson(String json, String expectedId) {
        JsonObject o = JsonParser.parseString(json).getAsJsonObject();
        String id = o.get("id").getAsString();
        if (!id.equals(expectedId)) throw new IllegalArgumentException("sidecar id " + id + " does not match its file " + expectedId);
        JsonObject pos = o.has("position") && o.get("position").isJsonObject() ? o.getAsJsonObject("position") : new JsonObject();
        JsonElement extra = o.get("extra");
        return new PhotoMetadata(id, integer(o, "number", 0), string(o, "name", ""), longValue(o, "capturedAt", 0L),
                string(o, "format", "png").toLowerCase(Locale.ROOT), integer(o, "width", 0), integer(o, "height", 0),
                o.has("favorite") && o.get("favorite").getAsBoolean(), string(o, "mode", "normal"),
                (float) decimal(o, "zoom", 1), (float) decimal(o, "fov", 0), string(o, "capture", "clean"),
                string(o, "dimension", ""), decimal(pos, "x", 0), decimal(pos, "y", 0), decimal(pos, "z", 0),
                (float) decimal(pos, "yaw", 0), (float) decimal(pos, "pitch", 0),
                extra != null && extra.isJsonObject() ? extra.getAsJsonObject() : null);
    }

    private static String string(JsonObject o, String key, String fallback) {
        return o.has(key) && o.get(key).isJsonPrimitive() ? o.get(key).getAsString() : fallback;
    }

    private static int integer(JsonObject o, String key, int fallback) {
        return o.has(key) && o.get(key).isJsonPrimitive() ? o.get(key).getAsInt() : fallback;
    }

    private static long longValue(JsonObject o, String key, long fallback) {
        return o.has(key) && o.get(key).isJsonPrimitive() ? o.get(key).getAsLong() : fallback;
    }

    private static double decimal(JsonObject o, String key, double fallback) {
        return o.has(key) && o.get(key).isJsonPrimitive() ? o.get(key).getAsDouble() : fallback;
    }
}
