package zcylas.totality.client.hud;

import com.mojang.blaze3d.pipeline.BlendFunction;
import com.mojang.blaze3d.pipeline.ColorTargetState;
import com.mojang.blaze3d.pipeline.RenderPipeline;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.resources.Identifier;
import org.joml.Matrix3x2fStack;
import zcylas.totality.Totality;

/**
 * Screen-space sprite drawing shared by the Voice Input and Power Mining HUDs: white-with-alpha
 * sprites (generated by {@code Totality-Research/voice-hud-operator/tools/generate_hud_textures.py})
 * tinted per state, placed with sub-pixel precision through the GUI pose, and either blended normally
 * or added (glows, bursts) through a GUI pipeline with additive blending.
 */
public final class HudSprites {

    /** Texels per GUI pixel in every HUD sprite. */
    public static final float DENSITY = 4;

    /**
     * Vanilla's textured GUI pipeline without face culling, so a sprite mirrored through the pose
     * (the right-hand bracket, ornaments) is not dropped as a back face.
     */
    public static final RenderPipeline NORMAL = RenderPipelines.register(RenderPipeline.builder(RenderPipelines.GUI_TEXTURED_SNIPPET)
            .withLocation(Identifier.fromNamespaceAndPath(Totality.MOD_ID, "pipeline/hud_textured"))
            .withCull(false)
            .build());
    /** The same with additive ("lightning") blending, for glows. */
    public static final RenderPipeline ADDITIVE = RenderPipelines.register(RenderPipeline.builder(RenderPipelines.GUI_TEXTURED_SNIPPET)
            .withLocation(Identifier.fromNamespaceAndPath(Totality.MOD_ID, "pipeline/hud_additive"))
            .withColorTargetState(new ColorTargetState(BlendFunction.LIGHTNING))
            .withCull(false)
            .build());

    /** A HUD sprite; {@code width}/{@code height} in texels. */
    public record Sprite(Identifier id, int width, int height) {
        public static Sprite of(String path, int width, int height) {
            return new Sprite(Identifier.fromNamespaceAndPath(Totality.MOD_ID, "textures/hud/" + path + ".png"), width, height);
        }

        /** Natural size in GUI pixels. */
        public float guiWidth() { return width / DENSITY; }
        public float guiHeight() { return height / DENSITY; }
    }

    private HudSprites() {}

    /** Draws {@code s} stretched over the GUI rectangle (x, y, w, h). */
    public static void draw(GuiGraphicsExtractor g, Sprite s, float x, float y, float w, float h, int argb, boolean additive) {
        if ((argb >>> 24) == 0 || w == 0 || h == 0) return;
        region(g, s, 0, s.width, x, y, w, h, argb, additive);
    }

    /** Draws {@code s} at its natural size centred on (cx, cy), scaled by {@code scale} and rotated by {@code radians}. */
    public static void drawCentred(GuiGraphicsExtractor g, Sprite s, float cx, float cy, float scale, float radians, int argb, boolean additive) {
        if ((argb >>> 24) == 0 || scale <= 0) return;
        Matrix3x2fStack pose = g.pose();
        pose.pushMatrix();
        pose.translate(cx, cy);
        if (radians != 0) pose.rotate(radians);
        float w = s.guiWidth() * scale, h = s.guiHeight() * scale;
        region(g, s, 0, s.width, -w / 2, -h / 2, w, h, argb, additive);
        pose.popMatrix();
    }

    /** Mirrored horizontally around its own centre (right-hand brackets, ornaments). */
    public static void drawMirrored(GuiGraphicsExtractor g, Sprite s, float x, float y, float w, float h, int argb, boolean additive) {
        if ((argb >>> 24) == 0) return;
        Matrix3x2fStack pose = g.pose();
        pose.pushMatrix();
        pose.translate(x + w, y);
        pose.scale(-1, 1);
        region(g, s, 0, s.width, 0, 0, w, h, argb, additive);
        pose.popMatrix();
    }

    /**
     * Horizontal 3-slice: the left and right {@code capGui} GUI pixels keep their proportions, the middle
     * stretches. The caps are {@code capGui * DENSITY} texels of the sprite.
     */
    public static void threeSlice(GuiGraphicsExtractor g, Sprite s, float x, float y, float w, float h, float capGui,
                                  int argb, boolean additive) {
        if ((argb >>> 24) == 0) return;
        float cap = Math.min(capGui, w / 2);
        int capTexels = Math.round(capGui * DENSITY);
        region(g, s, 0, capTexels, x, y, cap, h, argb, additive);
        region(g, s, capTexels, s.width - 2 * capTexels, x + cap, y, w - 2 * cap, h, argb, additive);
        region(g, s, s.width - capTexels, capTexels, x + w - cap, y, cap, h, argb, additive);
    }

    /** Texel columns [u, u + uWidth) of the whole sprite height into the GUI rectangle. */
    private static void region(GuiGraphicsExtractor g, Sprite s, int u, int uWidth, float x, float y, float w, float h,
                               int argb, boolean additive) {
        if (uWidth <= 0 || w <= 0 || h <= 0) return;
        Matrix3x2fStack pose = g.pose();
        pose.pushMatrix();
        pose.translate(x, y);
        pose.scale(w / uWidth, h / s.height);
        g.blit(additive ? ADDITIVE : NORMAL, s.id, 0, 0, u, 0, uWidth, s.height, uWidth, s.height,
                s.width, s.height, argb);
        pose.popMatrix();
    }

    // ── Colour helpers ────────────────────────────────────────────────────────

    public static int argb(float alpha, int rgb) {
        int a = Math.round(Math.max(0, Math.min(1, alpha)) * 255);
        return (a << 24) | (rgb & 0xFFFFFF);
    }

    public static int mix(int rgbA, int rgbB, float t) {
        t = Math.max(0, Math.min(1, t));
        int r = Math.round(((rgbA >> 16) & 0xFF) * (1 - t) + ((rgbB >> 16) & 0xFF) * t);
        int gr = Math.round(((rgbA >> 8) & 0xFF) * (1 - t) + ((rgbB >> 8) & 0xFF) * t);
        int b = Math.round((rgbA & 0xFF) * (1 - t) + (rgbB & 0xFF) * t);
        return (r << 16) | (gr << 8) | b;
    }
}
