package zcylas.totality.entity.dev;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

/**
 * DEVELOPMENT TEST entity {@code totality:slime_test} (V1 Small Slime visual integration test): the shipped geometry and
 * texture are the slime_base assets byte for byte, the hitbox agrees with the model's .bbmodel extents at the export's
 * render scale, the colour previews reuse the one texture and model, and the test entity is fully registered.
 */
class SlimeTestRegressionTest {

    private static final String ASSETS = "Context/Assets/Models/slime_base/";
    private static final String CLIENT = "src/main/java/zcylas/totality/client/entity/slime/";
    private static final String LIVE_TEXTURE = "src/main/resources/assets/totality/textures/entity/slime_test/slime_base.png";
    /** slime_base.png as delivered and export/SlimeBaseGeometry.java as regenerated by the fixed exporter. */
    private static final String TEXTURE_SHA256 = "996f28000df1a63357891ab8a5eafe79272ea6ce167478e8a0321aa2f92c2b5a";
    // Regenerated 2026-10-02 after the approved export_java.py top/bottom UV fix (before: ea0948d4...0fcf7371).
    private static final String GEOMETRY_SHA256 = "34d024c6f500390539fd3d2c4d7789bbe7268538fdb68d0c1e7692125ce5cf78";

    private static String read(String path) throws Exception {
        Path p = Path.of(path);
        assertTrue(Files.exists(p), "expected " + p);
        return Files.readString(p);
    }

    private static String sha256(String path) throws Exception {
        return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(Path.of(path))));
    }

    private static float number(String source, String regex) {
        Matcher m = Pattern.compile(regex).matcher(source);
        assertTrue(m.find(), regex);
        return Float.parseFloat(m.group(1));
    }

    @Test
    void shipsTheOriginalTextureAndGeometryUnchanged() throws Exception {
        assertEquals(TEXTURE_SHA256, sha256(LIVE_TEXTURE));
        assertEquals(GEOMETRY_SHA256, sha256(CLIENT + "SlimeBaseGeometry.java"));
        if (Files.exists(Path.of(ASSETS))) {
            assertEquals(TEXTURE_SHA256, sha256(ASSETS + "slime_base.png"));
            assertEquals(GEOMETRY_SHA256, sha256(ASSETS + "export/SlimeBaseGeometry.java"));
        }
    }

    @Test
    void hitboxMatchesTheModelAsRendered() throws Exception {
        float scale = number(read(CLIENT + "SlimeBaseGeometry.java"), "RENDER_SCALE = ([0-9.]+)F");
        String entities = read("src/main/java/zcylas/totality/init/ModEntities.java");
        String slime = entities.substring(entities.indexOf("SlimeTestEntity::new"));
        float width = number(slime, "\\.sized\\(([0-9.]+)f");
        float height = number(slime, "\\.sized\\([0-9.]+f, ([0-9.]+)f\\)");
        float eye = number(slime, "\\.eyeHeight\\(([0-9.]+)f\\)");

        if (!Files.exists(Path.of(ASSETS + "slime_base.bbmodel"))) return;
        JsonObject model = JsonParser.parseString(read(ASSETS + "slime_base.bbmodel")).getAsJsonObject();
        float[] min = {Float.MAX_VALUE, Float.MAX_VALUE, Float.MAX_VALUE};
        float[] max = {-Float.MAX_VALUE, -Float.MAX_VALUE, -Float.MAX_VALUE};
        for (JsonElement e : model.getAsJsonArray("elements")) {
            if (e.getAsJsonObject().get("name").getAsString().startsWith("eye")) continue;
            for (String corner : new String[]{"from", "to"}) {
                for (int i = 0; i < 3; i++) {
                    float v = e.getAsJsonObject().getAsJsonArray(corner).get(i).getAsFloat();
                    min[i] = Math.min(min[i], v);
                    max[i] = Math.max(max[i], v);
                }
            }
        }
        float blocks = scale / 16.0F;
        assertEquals((max[0] - min[0]) * blocks, width, 0.01F, "width = the body's widest extent");
        assertEquals((max[1] - min[1]) * blocks, height, 0.01F, "height = the body's rest height");
        assertTrue((max[2] - min[2]) * blocks <= width, "the square box covers the body's depth too");
        assertEquals(6.0F * blocks, eye, 0.01F, "eye height = the eye plates' centre (y 6)");
    }

    @Test
    void previewsReuseTheOneModelAndTexture() throws Exception {
        String renderer = read(CLIENT + "SlimeTestRenderer.java");
        String model = read(CLIENT + "SlimeTestModel.java");
        assertEquals(1, Pattern.compile("textures/entity/").matcher(renderer).results().count(), "one texture for every variant");
        assertEquals(3, Pattern.compile("SlimeBaseGeometry\\.createRoot\\(\\)").matcher(model).results().count(),
                "full model, body and eyes are all baked from the exported geometry");
        try (Stream<Path> textures = Files.list(Path.of(LIVE_TEXTURE).getParent())) {
            assertEquals(1, textures.filter(f -> f.toString().endsWith(".png")).count(),
                    "one source texture, no per-variant copies (element details are motif masks in motifs/)");
        }
        assertTrue(read("src/main/java/zcylas/totality/entity/dev/SlimeTestVariant.java").contains("GRAYSCALE(0xFFFFFFFF)"),
                "grayscale is the untinted original");
        for (String common : new String[]{"SlimeTestEntity", "SlimeTestVariant", "SlimeTestRenderMode"}) {
            assertFalse(read("src/main/java/zcylas/totality/entity/dev/" + common + ".java").contains("net.minecraft.client"),
                    common + " stays common code");
        }
    }

    @Test
    void isRegisteredAsADevelopmentEntity() throws Exception {
        assertTrue(read("src/main/java/zcylas/totality/init/ModEntities.java").contains("\"slime_test\""));
        assertTrue(read("src/main/java/zcylas/totality/Totality.java")
                .contains("FabricDefaultAttributeRegistry.register(ModEntities.SLIME_TEST, SlimeTestEntity.createAttributes());"));
        assertTrue(read("src/main/java/zcylas/totality/TotalityClient.java")
                .contains("EntityRenderers.register(ModEntities.SLIME_TEST, SlimeTestRenderer::new);"));
        assertTrue(read("src/main/generated/assets/totality/lang/en_us.json")
                .contains("\"entity.totality.slime_test\": \"Small Slime (Dev Test)\""));
    }
}
