package zcylas.totality.client.renderer.equipment;

import com.mojang.blaze3d.vertex.PoseStack;
import net.fabricmc.fabric.api.client.rendering.v1.LivingEntityRenderLayerRegistrationCallback;
import net.fabricmc.fabric.api.client.rendering.v1.RenderStateDataKey;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.model.player.PlayerModel;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.entity.RenderLayerParent;
import net.minecraft.client.renderer.entity.layers.RenderLayer;
import net.minecraft.client.renderer.entity.player.AvatarRenderer;
import net.minecraft.client.renderer.entity.state.AvatarRenderState;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.client.resources.model.EquipmentAssetManager;
import net.minecraft.client.resources.model.EquipmentClientInfo;
import net.minecraft.core.component.DataComponents;
import net.minecraft.resources.Identifier;
import net.minecraft.util.Mth;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.equipment.Equippable;
import org.joml.Matrix4f;
import org.joml.Vector3f;
import zcylas.totality.Totality;
import zcylas.totality.init.items.MagicItems;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Draws what a player wears in the Back equipment slot, on every player model (their own in third person and the
 * inventory preview, and every other player), from the render-only mirror synced to all watching clients. The only
 * Back item so far is the Cape of the Mountebank (Context/References/Other/Cape of the Mountebank Reference Sheet(1).png).
 * <p>Construction (128 x 64 box-UV texture, 1 texel per model unit). All cloth is zero-thickness planes, so panels
 * meet at shared edges instead of thick box ends, and no two faces of different parts lie in the same plane. The
 * render type culls back faces: a plane's outer face and its lining share their vertices, and without culling both
 * would be drawn at the same depth and speckle; with it only the face turned towards the camera is drawn:
 * <ul>
 *   <li>a centre column behind the torso and a rear column behind each arm, each three planes hinged exactly at their
 *       shared edges. The rear columns lie 0.15 outside the centre one and overlap it by one texel column painted
 *       identically, so the back reads as one sheet from behind even when a rear column is lifted by the arm below it;</li>
 *   <li>side tiers wrapping forward outside the arms, each hinged on its rear segment's outer edge (so the corner edge
 *       always coincides) with one splay. Each rear segment is a texel wider than the one above it, so the cloak flares
 *       towards the hem and each lower tier hangs outside the tier above; the upper tier reaches down inside it, so the
 *       wedge a bend opens at the tier seam is always covered (see MAX_FOLD_BACK). The top tier carries a shorter
 *       layer of cloth, the mantle's drop;</li>
 *   <li>on the body: a collar standing behind and beside the neck that turns with the head, cloth mantles over the
 *       shoulders (clear of the arms' swing), octagonal gold clasps and the chain; the hood lies on the upper centre
 *       of the back, riding its top segment.</li>
 * </ul>
 * <p>Motion is heavy cloth: one damped spring per segment towards a target bend (stiffer at the top, so the lower cloth
 * lags, overshoots a little and recovers), driven by vanilla's own cape signals with low gains, plus a slow idle wave.
 * On top of that the cloth makes room for the body: from the parent model's actual arm and leg poses (whatever
 * animation set them) the lift each segment of each column needs to stay behind the arms and legs is computed every
 * frame; a segment is lifted by that much at once and released gradually, and the cloth below it falls back towards
 * its natural hang, draping over the arm. Over chest armor (and leggings) the limbs are counted
 * with the armor's thickness and the cloak moves out; with an elytra the cloak is hidden (as vanilla hides its cape).
 * <p>Texture: textures/entity/equipment/cape_of_the_mountebank.png, generated by
 * Totality-Research/cape-geometry-fix/tools/cape_textures.py (its BOXES table matches the parts below).
 */
public class BackEquipmentLayer extends RenderLayer<AvatarRenderState, PlayerModel> {

    /** The Back item a player wears (set by AvatarRendererBackEquipmentMixin from the synced mirror), or null. */
    public static final RenderStateDataKey<Item> BACK_ITEM = RenderStateDataKey.create(() -> "totality:back_item");

    private static final Identifier CAPE_TEXTURE = Identifier.fromNamespaceAndPath(
            Totality.MOD_ID, "textures/entity/equipment/cape_of_the_mountebank.png");
    private static final RenderType CAPE_RENDER_TYPE = RenderTypes.entityCutoutCull(CAPE_TEXTURE);

    /** Segment lengths down the cloak (model units); the columns share them, so their hinges line up. */
    private static final float[] LENGTH = {8.0F, 7.0F, 8.0F};
    /**
     * Where the cloak hangs from, behind the shoulders (body space): from the mantles' underside (so no gap opens
     * between them), the centre plane, the rear planes 0.15 outside.
     */
    private static final float TOP_Y = -1.0F;
    private static final float CENTRE_Z = 2.4F;
    private static final float REAR_Z = 2.55F;
    /**
     * Rear columns start at |x| 3.5 (the centre column spans |x| <= 4.5, on the same texel grid) and widen by a texel
     * per segment: 3.5 .. 9.5, 10.5, 11.5.
     */
    private static final float REAR_INNER_X = 3.5F;
    private static final int[] REAR_WIDTH = {6, 7, 8};
    /** Outward splay of the side tiers (degrees), the same for every tier so the tier seams line up. */
    private static final float SPLAY = 12.0F;
    private static final int SIDE_DEPTH = 6;
    /**
     * How far a segment may fold back (forwards, towards the body) relative to the one above it (degrees), and how far
     * each upper side tier reaches down inside the tier below. A fold F turns the lower tier about the hinge's x axis,
     * which moves the overlap in the tiers' plane (covered up to atan(3 / 6) = 26.6 deg of wedge) and, because the
     * tiers are splayed, across it: a strip corner TIER_OVERLAP from the hinge and SIDE_DEPTH forward by at most
     * sin(SPLAY) * (TIER_OVERLAP * sin F + SIDE_DEPTH * (1 - cos F)) = 0.36, well inside the 0.98 between the tiers
     * (one texel of flare, along the tier's normal).
     */
    private static final float MAX_FOLD_BACK = 24.0F;
    private static final int TIER_OVERLAP = 3;
    /** The mantle's drop lies this far outside the top tier (a layer of cloth; it moves with the tier). */
    private static final float DROP_OUT = 0.3F;
    /** Spring stiffness and damping per segment (per tick): the lower the segment, the softer and later. */
    private static final float[] STIFFNESS = {0.30F, 0.17F, 0.11F};
    private static final float[] DAMPING = {0.60F, 0.44F, 0.35F};
    /** How far the cloth keeps from a limb (model units), and how fast a lift by a limb relaxes (ticks). */
    private static final float CLEARANCE = 0.6F;
    private static final float LIFT_RELAX_TICKS = 5.0F;
    /** Over chest armor the rear columns widen by a unit (from their inner edges; the scale carries down the column). */
    private static final float ARMOR_WIDEN = (REAR_WIDTH[0] + 1.0F) / REAR_WIDTH[0];

    private static final int CENTRE = 0;
    private static final int LEFT = 1;
    private static final int RIGHT = 2;

    private final EquipmentAssetManager equipmentAssets;
    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart cloak;
    private final ModelPart[][] column = new ModelPart[3][3];
    private final ModelPart collar;
    private final ModelPart mantleLeft;
    private final ModelPart mantleRight;
    private final ModelPart claspLeft;
    private final ModelPart claspRight;
    private final ModelPart chain;
    private final Map<Integer, Cloth> cloths = new HashMap<>();
    private int framesSincePrune;

    public BackEquipmentLayer(RenderLayerParent<AvatarRenderState, PlayerModel> renderer, EquipmentAssetManager equipmentAssets) {
        super(renderer);
        this.equipmentAssets = equipmentAssets;
        this.root = createCape().bakeRoot();
        this.body = root.getChild("body");
        this.cloak = body.getChild("cloak");
        String[] names = {"centre", "rear_left", "rear_right"};
        for (int c = 0; c < 3; c++) {
            ModelPart part = cloak.getChild(names[c] + "_1");
            for (int k = 0; k < 3; k++) {
                column[c][k] = part;
                if (k < 2) part = part.getChild(names[c] + "_" + (k + 2));
            }
        }
        this.collar = body.getChild("collar");
        this.mantleLeft = body.getChild("mantle_left");
        this.mantleRight = body.getChild("mantle_right");
        this.claspLeft = body.getChild("clasp_left");
        this.claspRight = body.getChild("clasp_right");
        this.chain = body.getChild("chain");
    }

    /** Adds this layer to every player (avatar) renderer. */
    public static void register() {
        LivingEntityRenderLayerRegistrationCallback.EVENT.register((entityType, renderer, helper, context) -> {
            if (renderer instanceof AvatarRenderer<?> avatarRenderer) {
                helper.register(new BackEquipmentLayer(avatarRenderer, context.getEquipmentAssets()));
            }
        });
    }

    /**
     * Model units: the body part's origin is the neck; +y is down, -z is the front (the face), +z the back. The player
     * body spans x -4..4, z -2..2, y 0..12; the arms x 4..8 either side (slim 4..7); the legs reach y 24. The left
     * side (+x) uses the texture as authored and the right side mirrors it (outward faces cloth, inner faces lining).
     */
    private static LayerDefinition createCape() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.ZERO);

        // Collar: behind and beside the neck, turning with the head (so the head does not cut through it).
        PartDefinition collar = body.addOrReplaceChild("collar", CubeListBuilder.create(), PartPose.ZERO);
        // (the back piece stands above the cloak's top edge, so turning with the head it never cuts into the cloak)
        collar.addOrReplaceChild("back", CubeListBuilder.create().texOffs(80, 0).addBox(-5.0F, -6.0F, 4.3F, 10, 5, 2), PartPose.ZERO);
        collar.addOrReplaceChild("left", CubeListBuilder.create().texOffs(104, 0).addBox(4.4F, -5.1F, -1.7F, 1, 3, 6), PartPose.ZERO);
        collar.addOrReplaceChild("right", CubeListBuilder.create().texOffs(104, 0).mirror().addBox(-5.4F, -5.1F, -1.7F, 1, 3, 6), PartPose.ZERO);
        // Shoulder mantles, a unit above the shoulders so the arms' top corners pass under them.
        body.addOrReplaceChild("mantle_left", CubeListBuilder.create().texOffs(80, 16).addBox(3.5F, -2.0F, -3.0F, 7, 1, 6), PartPose.ZERO);
        body.addOrReplaceChild("mantle_right", CubeListBuilder.create().texOffs(80, 16).mirror().addBox(-10.5F, -2.0F, -3.0F, 7, 1, 6), PartPose.ZERO);
        // Clasps (clear of the mantles above them) and the chain between their inner faces.
        body.addOrReplaceChild("clasp_left", CubeListBuilder.create().texOffs(0, 26).addBox(2.2F, -0.4F, -3.4F, 3, 3, 1), PartPose.ZERO);
        body.addOrReplaceChild("clasp_right", CubeListBuilder.create().texOffs(0, 26).mirror().addBox(-5.2F, -0.4F, -3.4F, 3, 3, 1), PartPose.ZERO);
        body.addOrReplaceChild("chain", CubeListBuilder.create().texOffs(8, 26).addBox(-2.0F, 1.2F, -2.9F, 4, 3, 0), PartPose.ZERO);

        // The cloak: twisted as a whole (turning), made of three columns of hinged planes.
        PartDefinition cloak = body.addOrReplaceChild("cloak", CubeListBuilder.create(), PartPose.ZERO);
        int[] rowV = {0, 8, 15};
        int[] sideU = {0, 12, 24};
        PartDefinition centre = cloak;
        PartDefinition left = cloak;
        PartDefinition right = cloak;
        for (int k = 0; k < 3; k++) {
            int h = (int) LENGTH[k];
            PartPose below = k == 0 ? null : PartPose.offset(0.0F, LENGTH[k - 1], 0.0F);
            centre = centre.addOrReplaceChild("centre_" + (k + 1),
                    CubeListBuilder.create().texOffs(0, rowV[k]).addBox(-4.5F, 0.0F, 0.0F, 9, h, 0),
                    k == 0 ? PartPose.offset(0.0F, TOP_Y, CENTRE_Z) : below);
            int w = REAR_WIDTH[k];
            left = left.addOrReplaceChild("rear_left_" + (k + 1),
                    CubeListBuilder.create().texOffs(18, rowV[k]).addBox(0.0F, 0.0F, 0.0F, w, h, 0),
                    k == 0 ? PartPose.offset(REAR_INNER_X, TOP_Y, REAR_Z) : below);
            right = right.addOrReplaceChild("rear_right_" + (k + 1),
                    CubeListBuilder.create().texOffs(34, rowV[k]).addBox(-w, 0.0F, 0.0F, w, h, 0),
                    k == 0 ? PartPose.offset(-REAR_INNER_X, TOP_Y, REAR_Z) : below);
            // Side tiers on the rear segments' outer edges, splayed; all but the last reach down inside the next.
            int down = k < 2 ? TIER_OVERLAP : 0;
            PartDefinition sideLeft = left.addOrReplaceChild("side", CubeListBuilder.create().texOffs(sideU[k], 30)
                            .addBox(0.0F, 0.0F, -SIDE_DEPTH, 0, h + down, SIDE_DEPTH),
                    PartPose.offsetAndRotation(w, 0.0F, 0.0F, 0.0F, -SPLAY * Mth.DEG_TO_RAD, 0.0F));
            PartDefinition sideRight = right.addOrReplaceChild("side", CubeListBuilder.create().texOffs(sideU[k], 30).mirror()
                            .addBox(0.0F, 0.0F, -SIDE_DEPTH, 0, h + down, SIDE_DEPTH),
                    PartPose.offsetAndRotation(-w, 0.0F, 0.0F, 0.0F, SPLAY * Mth.DEG_TO_RAD, 0.0F));
            if (k == 0) {
                sideLeft.addOrReplaceChild("mantle_drop", CubeListBuilder.create().texOffs(106, 16).mirror()
                        .addBox(DROP_OUT, 0.0F, -SIDE_DEPTH, 0, 4, SIDE_DEPTH), PartPose.ZERO);
                sideRight.addOrReplaceChild("mantle_drop", CubeListBuilder.create().texOffs(106, 16)
                        .addBox(-DROP_OUT, 0.0F, -SIDE_DEPTH, 0, 4, SIDE_DEPTH), PartPose.ZERO);
            }
            if (k == 0) {
                // The hood lies on the centre of the back, 0.45 outside its plane (0.3 outside the rear columns).
                centre.addOrReplaceChild("hood_drape",
                        CubeListBuilder.create().texOffs(80, 7).addBox(-4.0F, 0.4F, 0.45F, 8, 7, 2), PartPose.ZERO);
            }
        }
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public void submit(PoseStack poseStack, SubmitNodeCollector collector, int lightCoords, AvatarRenderState state, float yRot, float xRot) {
        if (state.isInvisible || state.getData(BACK_ITEM) != MagicItems.CAPE_OF_THE_MOUNTEBANK) return;
        pose(state);
        collector.submitModelPart(root, poseStack, CAPE_RENDER_TYPE, lightCoords, OverlayTexture.NO_OVERLAY, null, -1, null, state.outlineColor);
    }

    private void pose(AvatarRenderState state) {
        PlayerModel parent = getParentModel();
        root.getAllParts().forEach(ModelPart::resetPose);
        body.loadPose(parent.body.storePose());

        boolean wings = hasLayer(state.chestEquipment, EquipmentClientInfo.LayerType.WINGS);
        boolean chestArmor = !state.chestEquipment.isEmpty() && !wings;
        boolean helmet = hasLayer(state.headEquipment, EquipmentClientInfo.LayerType.HUMANOID);
        cloak.visible = !wings;
        if (chestArmor) {
            // Vanilla's outer armor layer is one unit thicker all round: the cloak and the shoulder cloth move out.
            // The rear columns widen outwards from their inner edges (their side tiers ride on the outer edges), and the
            // cloak and collar rise with the mantles.
            cloak.z += 1.0F;
            cloak.y -= 1.0F;
            collar.y -= 1.0F;
            column[LEFT][0].xScale = ARMOR_WIDEN;
            column[RIGHT][0].xScale = ARMOR_WIDEN;
            mantleLeft.y -= 1.0F;
            mantleRight.y -= 1.0F;
            claspLeft.z -= 1.0F;
            claspRight.z -= 1.0F;
            chain.z -= 1.0F;
        }
        if (helmet || chestArmor) {
            collar.z += 1.0F;
            collar.xScale = 1.1F;
        }
        // The collar turns with the head (the head's yaw is relative to the body in HumanoidModel).
        collar.yRot = Math.clamp(parent.head.yRot, -1.1F, 1.1F) * 0.9F;

        Cloth cloth = simulate(state);
        float[][] lift = clearance(state, parent, cloth, chestArmor);
        cloak.zRot = cloth.twist * Mth.DEG_TO_RAD;
        for (int c = 0; c < 3; c++) {
            for (int k = 0; k < 3; k++) {
                // Lifts are absolute: a segment lifted over a limb does not carry the segments below it along.
                float above = k == 0 ? 0.0F : lift[c][k - 1];
                column[c][k].xRot = (cloth.angle[k] + lift[c][k] - above) * Mth.DEG_TO_RAD;
            }
        }
    }

    /** One player's cloak: a bend angle and its velocity per segment, the twist, and the limb lifts per column. */
    private static final class Cloth {
        final float[] angle = new float[3];
        final float[] velocity = new float[3];
        float twist;
        float twistVelocity;
        final float[][] lift = new float[3][3];
        float lastAge = Float.NaN;
        float dt;
        long lastSeen;
    }

    /**
     * Steps this player's cloak to the render state's time. Targets come from vanilla's cape signals (which already
     * trail the player) with low gains: lean (moving, capped) bends the cloak a little at the top and more lower down;
     * flap (jump, fall, stride bounce) lifts the hem; crouching turns the cloak back towards hanging straight down
     * against the body's forward pitch; lean2 (turning, strafing) twists it; a slow wave runs down it when idle.
     */
    private Cloth simulate(AvatarRenderState state) {
        float lean = Math.min(state.capeLean, 120.0F);
        float flap = state.capeFlap;
        float lift = Math.max(0.0F, flap);
        float age = state.ageInTicks;
        float idle1 = Mth.sin(age * 0.071F) * 1.2F;
        float idle2 = Mth.sin(age * 0.071F - 1.3F) * 1.8F;
        float[] target = {
                4.0F + 0.16F * lean + 0.10F * flap + (state.isCrouching ? -7.0F : 0.0F),
                3.0F + 0.08F * lean + 0.06F * lift + idle1,
                3.5F + 0.10F * lean + 0.10F * lift + idle2
        };
        float twistTarget = -0.25F * state.capeLean2;

        Cloth cloth = cloths.computeIfAbsent(state.id, id -> new Cloth());
        float dt = Float.isNaN(cloth.lastAge) ? -1.0F : age - cloth.lastAge;
        if (dt < 0.0F || dt > 40.0F) {
            // First sight of this player (or a reset of its age): start at rest in the target pose.
            System.arraycopy(target, 0, cloth.angle, 0, 3);
            Arrays.fill(cloth.velocity, 0.0F);
            cloth.twist = twistTarget;
            cloth.twistVelocity = 0.0F;
            for (float[] l : cloth.lift) Arrays.fill(l, 0.0F);
            dt = 0.0F;
        } else if (dt > 0.0F) {
            int steps = Mth.ceil(dt / 0.25F);
            float h = dt / steps;
            for (int s = 0; s < steps; s++) {
                for (int i = 0; i < 3; i++) {
                    cloth.velocity[i] += (STIFFNESS[i] * (target[i] - cloth.angle[i]) - DAMPING[i] * cloth.velocity[i]) * h;
                    cloth.angle[i] += cloth.velocity[i] * h;
                }
                cloth.twistVelocity += (STIFFNESS[1] * (twistTarget - cloth.twist) - DAMPING[1] * cloth.twistVelocity) * h;
                cloth.twist += cloth.twistVelocity * h;
            }
        }
        // Heavy cloth never folds over itself or lifts past horizontal behind the wearer (the top segment may turn
        // further forward, against the body's own forward pitch, while crouching).
        for (int i = 0; i < 3; i++) cloth.angle[i] = Math.clamp(cloth.angle[i], i == 0 ? -9.0F : -4.0F, 40.0F);
        cloth.dt = dt;
        cloth.lastAge = age;
        cloth.lastSeen = System.nanoTime();
        if (++framesSincePrune > 600) {
            framesSincePrune = 0;
            long stale = System.nanoTime() - 10_000_000_000L;
            cloths.values().removeIf(c -> c.lastSeen < stale);
        }
        return cloth;
    }

    /**
     * How far (degrees, per column and segment) each segment is lifted beyond its natural hang to stay behind the arms
     * and legs as the parent model has actually posed them this frame. The back faces of the limbs (with their outer
     * layer or armor) are sampled, taken into the body's frame, and walked down each column: where a point lies behind
     * a segment's line, that segment is lifted just enough to clear it. Lifts are absolute, so below a lifted segment
     * the cloth falls back towards its natural hang (it drapes over the arm instead of lifting whole). A lift applies
     * at once and relaxes over a few ticks, as cloth lifted by a swinging arm falls back. Every column clears whatever
     * limb points lie across it (the centre column reaches over the arms' inner edges, so an arm swinging back lifts it
     * with the rear column). A rear segment is never lifted less than the centre one beside it, so the centre plane
     * cannot pass through the strip where a rear column overlaps it.
     */
    private float[][] clearance(AvatarRenderState state, PlayerModel parent, Cloth cloth, boolean chestArmor) {
        Matrix4f toBody = partMatrix(parent.body).invert();
        // The limbs' outer layer: the sleeves and trousers (0.25 out), or the armor over them. The arm's edges are those
        // of the wide model (right arm x -3 .. 1); the slim arm (-2 .. 1) lies within them.
        float armLayer = chestArmor ? 1.0F : 0.25F;
        float legLayer = state.legsEquipment.isEmpty() ? 0.25F : 0.5F;
        List<Vector3f> arms = new ArrayList<>();
        List<Vector3f> legs = new ArrayList<>();
        for (float y : new float[]{2.0F, 5.0F, 8.0F, 10.0F + armLayer}) {
            for (float x : new float[]{-3.0F - armLayer, -1.0F, 1.0F + armLayer}) {
                arms.add(limbPoint(parent.rightArm, x, y, 2.0F + armLayer, toBody));
                arms.add(limbPoint(parent.leftArm, -x, y, 2.0F + armLayer, toBody));
            }
        }
        for (float y : new float[]{4.0F, 8.0F, 12.0F + legLayer}) {
            for (float x : new float[]{-2.0F - legLayer, 0.0F, 2.0F + legLayer}) {
                legs.add(limbPoint(parent.rightLeg, x, y, 2.0F + legLayer, toBody));
                legs.add(limbPoint(parent.leftLeg, x, y, 2.0F + legLayer, toBody));
            }
        }
        float relax = cloth.dt <= 0.0F ? 1.0F : (float) Math.exp(-cloth.dt / LIFT_RELAX_TICKS);
        float out = chestArmor ? 1.0F : 0.0F;
        float widen = chestArmor ? ARMOR_WIDEN : 1.0F;
        for (int c = 0; c < 3; c++) {
            float y = TOP_Y - out;
            float z = (c == CENTRE ? CENTRE_Z : REAR_Z) + out;
            float natural = 0.0F;
            for (int k = 0; k < 3; k++) {
                float width = REAR_WIDTH[k] * widen;
                float minX = c == CENTRE ? -4.5F : c == LEFT ? REAR_INNER_X : -REAR_INNER_X - width;
                float maxX = c == CENTRE ? 4.5F : c == LEFT ? REAR_INNER_X + width : -REAR_INNER_X;
                natural += cloth.angle[k];
                float needed = 0.0F;
                for (List<Vector3f> points : List.of(arms, legs)) {
                    for (Vector3f p : points) {
                        if (p.x < minX || p.x > maxX) continue;
                        float dy = p.y - y;
                        if (dy < 0.5F || dy > LENGTH[k] + 2.0F) continue;
                        float required = (float) Math.toDegrees(Math.atan2(p.z + CLEARANCE - z, dy));
                        needed = Math.max(needed, required - natural);
                    }
                }
                cloth.lift[c][k] = Math.max(needed, cloth.lift[c][k] * relax);
                if (k > 0) {
                    // Fold back at most MAX_FOLD_BACK from the segment above (lifting this one, never less clearance).
                    cloth.lift[c][k] = Math.max(cloth.lift[c][k], cloth.lift[c][k - 1] - cloth.angle[k] - MAX_FOLD_BACK);
                }
                float a = (natural + cloth.lift[c][k]) * Mth.DEG_TO_RAD;
                y += LENGTH[k] * Mth.cos(a);
                z += LENGTH[k] * Mth.sin(a);
            }
        }
        for (int k = 0; k < 3; k++) {
            cloth.lift[LEFT][k] = Math.max(cloth.lift[LEFT][k], cloth.lift[CENTRE][k]);
            cloth.lift[RIGHT][k] = Math.max(cloth.lift[RIGHT][k], cloth.lift[CENTRE][k]);
        }
        return cloth.lift;
    }

    /** A point on the back face of a limb (limb-local x, y along the limb, z = its back), in the body's frame. */
    private static Vector3f limbPoint(ModelPart limb, float x, float y, float z, Matrix4f toBody) {
        Vector3f p = partMatrix(limb).transformPosition(new Vector3f(x, y, z));
        return toBody.transformPosition(p);
    }

    /** The part's pose as ModelPart#translateAndRotate applies it (model units). */
    private static Matrix4f partMatrix(ModelPart part) {
        return new Matrix4f().translate(part.x, part.y, part.z).rotateZYX(part.zRot, part.yRot, part.xRot);
    }

    /** Same test as vanilla's CapeLayer: does the worn item draw this equipment layer (e.g. WINGS for an elytra)? */
    private boolean hasLayer(ItemStack stack, EquipmentClientInfo.LayerType layerType) {
        Equippable equippable = stack.get(DataComponents.EQUIPPABLE);
        if (equippable == null || equippable.assetId().isEmpty()) return false;
        return !equipmentAssets.get(equippable.assetId().get()).getLayers(layerType).isEmpty();
    }
}
